server:
  port: 8081

spring:
  profiles:
    active: dev
  #application
  application:
    name: cloud-service-1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      #解决升级后，启动循环依赖报错问题
      filter:
        enabled: false
      transport:
        dashboard: localhost:8858
        heartbeat-interval-ms: 500
      eager: true
      datasource:
        ds1:
          file:
            file: classpath:degraderule.json
            dataType: json
            ruleType: degrade
  batch:
    jdbc:
      platform: mysql
      initialize-schema: always #初始化

  datasource:
    db1:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      jdbc-url: jdbc:mysql://localhost:3306/new_schema?serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver




logging:
  #  config: classpath:log4j.xml
  config: classpath:logback.xml